ENH: skip setting rpath if uneeded
FFY00/meson-python pull request #139
Opened 2022-09-13 22:31 UTC by FFY00

I also fixed `ELF.rpath`, which is needed for the tests, and added a test for setting the rpath in the first place in this PR.

2022-09-14 09:09 UTC, rgommers requested changes
Thanks @FFY00. There are some issues shown by the CI results. The code change looks like an improvement, and will solve the most important part of gh-125. It looks like it won't yet solve the unnecessary dependency issue. That can be left for later if you prefer.

2022-09-14 09:09 UTC, rgommers commented on tests/test_wheel.py
> +def test_rpath(wheel_link_against_local_lib, tmpdir):
These added test should should be skipped unless the platform is `linux`.

2022-09-14 09:09 UTC, rgommers commented on mesonpy/_elf.py
> +            rpath = self._patchelf('--print-rpath').strip()
This doesn't work portably it looks like. For example [in this CI log](https://github.com/FFY00/meson-python/actions/runs/3049095667/jobs/4914826119#step:7:340):
```
 E               subprocess.CalledProcessError: Command '['patchelf', '--print-rpath', '/tmp/pytest-of-runner/pytest-0/test_uneeded_rpath0/purelib_and_platlib-1.0.0.data/platlib/plat.{EXT_SUFFIX}']' returned non-zero exit status 1.
```

2022-09-27 18:41 UTC, rgommers commented
Ugh, this still depends on other fixes:
```
patchelf: getting info about '/tmp/pytest-of-runner/pytest-0/test_unneeded_r"
 b"path0/plat.cpython-39-x86_64-linux-gnu.so': No such file or directory
```
That's because the test package it's built on is still xfailed:
```python
@pytest.mark.xfail(reason='Meson bug')
def test_purelib_and_platlib(wheel_purelib_and_platlib):
    artifact = wheel.wheelfile.WheelFile(wheel_purelib_and_platlib)

    expecting = {
        f'plat{EXT_SUFFIX}',
```
This passes locally with Meson master. After the other open PR for tags is merged, it should pass with released Meson as well.

2022-09-28 15:54 UTC, rgommers commented
You just lost the commits that made this PR pass CI. I'll re-add them.

2022-09-28 15:56 UTC, FFY00 commented
Sorry :sweat_smile:

2022-09-28 16:28 UTC, rgommers commented
I think that's it, but hard to be sure since I had to manually re-apply fixes. Let's first ensure CI is green, and then if desired at the end rewrite history to the desired commit granularity.

2022-09-28 16:51 UTC, FFY00 commented
I have squashed the fix with the affected commit, the tests seem to be passing, are you okay with me pushing?

2022-09-28 17:01 UTC, rgommers commented
Sure, go ahead. CI is green (codecov isn't relevant, and Sage isn't currently testing the right thing). So rewrite history as you wish and then merge it I'd say.

2022-09-28 20:03 UTC, merged